### ISSUE TITLE
Bug: reconciler/sharing.ts calls getSonnetJson() which has no export in bedrock.ts

### ISSUE THREAD

**Issue by slam-paws** [shantamg/meet-without-fear#644]
## Summary

`reconciler/sharing.ts` calls `getSonnetJson()` but this function does not exist as an export in `bedrock.ts`. This is a potential production crash — if the sharing reconciler code path is hit at runtime, it will throw a `TypeError: getSonnetJson is not a function` error.

## Flagged by

Docs audit bot (2026-05-23) while reviewing changes from PRs #640/#641 (Stage 3/4 rework + Tending flow). Posted to #agentic-devs but no GitHub issue existed yet.

## Steps to Reproduce

1. Trigger any code path in the sharing reconciler that calls `getSonnetJson()`
2. Observe `TypeError: getSonnetJson is not a function`

## Impact

- If the path is reachable in production, users could see silent failures or crashes in the sharing/tending flow
- Needs verification: confirm whether `getSonnetJson` was removed from `bedrock.ts` as part of the Stage 3/4 rework, or was never added

## Suggested Investigation

- [ ] Check `bedrock.ts` for all exports — does `getSonnetJson` exist anywhere?
- [ ] Check `reconciler/sharing.ts` — where is `getSonnetJson()` called and is the path reachable?
- [ ] If removed: add it back or replace the call with the correct function
- [ ] If never added: this is a gap introduced in PR #640

🤖 Filed by Slam Paws (daily-strategy, 2026-05-23)

**Comment by slam-paws** [comment]
## Investigation Report

**Root cause**: No bug exists — false positive from docs audit.

**Evidence**:
- `sharing.ts:36` imports `getSonnetJson` from `'./analysis'` (not from `bedrock.ts`)
- `reconciler/analysis.ts:72` exports `getSonnetJson` as a public async function — the import resolves correctly
- `bedrock.ts` exports `getSonnetResponse` and `getSonnetStreamingResponse` — separate functions, not involved
- TypeScript compiles with zero errors for all affected files (`npx tsc --noEmit` clean)

**Recommendation**: Close as not-a-bug. The docs audit bot likely confused `getSonnetJson` (in `analysis.ts`) with `getSonnetResponse` (in `bedrock.ts`) due to similar naming and filed a false positive.

**Next step**: Removing `bot:investigate` and `bug` labels — no fix needed. Closing issue.
